name: cnetv_mobile_new
description: A stable version of CNETV mobile app for Flutter 3.35.x
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.35.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & State
  cupertino_icons: 1.0.8
  flutter_bloc: 8.1.6
  equatable: 2.0.7

  # Networking
  dio: 5.7.0
  http: 1.2.2

  # Storage & Local DB
  shared_preferences: 2.2.3
  hive: 2.2.3
  hive_flutter: 1.1.0
  path_provider: 2.1.5

  # Firebase & Notifications
  firebase_core: 3.8.0
  firebase_messaging: 15.1.3
  flutter_local_notifications: 17.2.3

  # Media & Files
  cached_network_image: 3.4.1
  file_picker: 8.1.2
  image_picker: 1.1.2
  video_player: 2.9.2
  chewie: 1.8.5
  photo_view: 0.15.0

  # Web & Deep Linking
  url_launcher: 6.3.1
  url_launcher_linux: 3.2.1
  url_launcher_windows: 3.1.4

  # Social & Sharing
  share_plus: 11.1.0

  # Utils
  intl: 0.19.0
  flutter_svg: 2.0.10+1
  connectivity_plus: 6.1.1
  device_info_plus: 12.1.0
  package_info_plus: 8.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
