name: cnetv_mobile_new
description: A stable version of CNETV mobile app for Flutter 3.37.x
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.37.0-0.0.pre <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core UI
  cupertino_icons: 1.0.8
  page_transition: 2.2.1
  flutter_staggered_grid_view: 0.7.0
  loading_overlay: 0.4.3
  carousel_slider: 5.1.1
  fluttertoast: 8.2.12

  # Networking
  http: 1.5.0
  dio: 5.9.0

  # State management
  provider: 6.1.2

  # Storage & Preferences
  shared_preferences: 2.3.3
  path_provider: 2.1.4
  flutter_secure_storage: 9.0.0   # ✅ Added secure storage

  # Utilities
  url_launcher: 6.3.1
  share_plus: 12.0.0
  json_annotation: 4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0
  flutter_launcher_icons: 0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
    - assets/json/mock_ads.json
    - assets/svgs/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Black.ttf
          weight: 900
        - asset: assets/fonts/Lato-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Thin.ttf
          weight: 100
